import test from 'node:test';
import assert from 'node:assert/strict';
import { StagingRpcTransport } from '../src/escrita/transport-staging.mjs';
class Socket extends EventTarget {
 readyState=1;url='wss://isolated-control.example.test/ws?orchestrationProtocol=2';sent=[];
 send(data){this.sent.push(JSON.parse(data));}
 receive(frame){this.dispatchEvent(new MessageEvent('message',{data:JSON.stringify(frame)}));}
 close(){this.readyState=3;this.dispatchEvent(new Event('close'));}
}
function setup(){const socket=new Socket();let failures=0;const transport=new StagingRpcTransport({socket,onFailure:()=>failures++});return {socket,transport,failures:()=>failures};}
test('actual Effect Request/Exit framing; no JSON-RPC envelope or retry',async()=>{const s=setup(),payload={type:'thread.delete',commandId:'c',threadId:'t'},p=s.transport.invoke('orchestration.dispatchCommand',payload);assert.deepEqual(s.socket.sent,[{_tag:'Request',id:'1',tag:'orchestration.dispatchCommand',payload,headers:[]}]);s.socket.receive({_tag:'Exit',requestId:'1',exit:{_tag:'Success',value:{sequence:7}}});assert.deepEqual(await p,{sequence:7});s.socket.receive({_tag:'Exit',requestId:'1',exit:{_tag:'Success',value:{sequence:7}}});assert.equal(s.socket.sent.length,1);s.transport.close();});
test('failure frame and socket loss close authority, no reconnect',async()=>{for(const kind of ['failure','close','malformed','wrongReceipt']){const s=setup(),p=s.transport.invoke('orchestration.dispatchCommand',{type:'thread.delete'});if(kind==='close')s.socket.close();else s.socket.receive(kind==='failure'?{_tag:'Exit',requestId:'1',exit:{_tag:'Failure',cause:[{secret:'must never leak'}]}}:kind==='malformed'?{bad:'frame'}:{_tag:'Exit',requestId:'1',exit:{_tag:'Success',value:{threadId:'t',projection:{},resumed:false}}});await assert.rejects(p,/^Error: control_transport_uncertain$/);assert.equal(s.failures(),1);assert.throws(()=>s.transport.invoke('orchestration.dispatchCommand',{}));assert.equal(s.socket.sent.length,1);}});
test('closed, insecure and wrong protocol sockets rejected before dispatch',()=>{for(const url of ['ws://localhost/ws?orchestrationProtocol=2','wss://control/ws','wss://control/wrong?orchestrationProtocol=2']) {const s=new Socket();s.url=url;assert.throws(()=>new StagingRpcTransport({socket:s,onFailure:()=>{}}));}const s=setup();assert.throws(()=>s.transport.invoke('server.auth.createPairingLink',{}));assert.equal(s.socket.sent.length,0);s.transport.close();});
test('launch receipt sanitized; pending request cap does not send extras',async()=>{const socket=new Socket(),transport=new StagingRpcTransport({socket,onFailure:()=>{},maxPending:1}),p=transport.invoke('orchestration.launchThread',{projectId:'p'});assert.throws(()=>transport.invoke('orchestration.launchThread',{}),/too_many_dispatches/);socket.receive({_tag:'Exit',requestId:'1',exit:{_tag:'Success',value:{threadId:'t',resumed:false,projection:{private:'no output'}}}});assert.deepEqual(transport.receipt(await p),{threadId:'t',resumed:false});assert.equal(socket.sent.length,1);transport.close();});
test('failing authority callback still rejects every pending call',async()=>{const socket=new Socket(),transport=new StagingRpcTransport({socket,onFailure:()=>{throw new Error('audit failed');}}),p=transport.invoke('orchestration.dispatchCommand',{});socket.close();await assert.rejects(p,/control_transport_uncertain/);});

test('typed frame sanitized: empty or malformed tag is uncertain; cause, code and nested fields never leave; strings clipped',async()=>{
 for(const tag of ['','1bad','a b',{},null]) {const s=setup(),p=s.transport.invoke('orchestration.dispatchCommand',{},{nativeErrors:true});s.socket.receive({_tag:'Exit',requestId:'1',exit:{_tag:'Failure',cause:[{_tag:'Fail',error:{_tag:tag,message:'m'}}]}});await assert.rejects(p,/control_transport_uncertain/);assert.equal(s.failures(),1);}
 const s=setup(),p=s.transport.invoke('orchestration.dispatchCommand',{},{nativeErrors:true});
 s.socket.receive({_tag:'Exit',requestId:'1',exit:{_tag:'Failure',cause:[{_tag:'Fail',error:{_tag:'OrchestrationV2DispatchCommandError',message:'m'.repeat(3000),detail:'d'.repeat(3000),cause:'SYNTHETIC_PRIVATE',code:'overrides_tag',nested:{secret:1},commandId:'c',n:1,b:true,['k'.repeat(65)]:true,'bad-name':true}}]}});
 await assert.rejects(p,e=>{assert.deepEqual(Object.keys(e.native).sort(),['b','code','commandId','detail','message','n']);assert.equal(e.native.code,'OrchestrationV2DispatchCommandError');assert.equal(e.native.message.length,2000);assert.equal(e.native.detail.length,2000);return true;});
 assert.equal(s.failures(),0);assert.equal(s.transport.available,true);
});
